// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxugPiBT7P6cXCXJjD_bYElulc2nM1G0',
    appId: '1:804095641312:web:0b97823199234a34eb7285',
    messagingSenderId: '804095641312',
    projectId: 'folder-ver2',
    authDomain: 'folder-ver2.firebaseapp.com',
    storageBucket: 'folder-ver2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMQuC2Y8GicVxPXEEpgUkR1ohAfRI8hQ',
    appId: '1:804095641312:android:91a3137ded5a6000eb7285',
    messagingSenderId: '804095641312',
    projectId: 'folder-ver2',
    storageBucket: 'folder-ver2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQkZruabMWNvvBRSl7ETEQAgOOxUzC9Ws',
    appId: '1:804095641312:ios:7c32e1406a3c178deb7285',
    messagingSenderId: '804095641312',
    projectId: 'folder-ver2',
    storageBucket: 'folder-ver2.appspot.com',
    iosBundleId: 'com.example.folder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQkZruabMWNvvBRSl7ETEQAgOOxUzC9Ws',
    appId: '1:804095641312:ios:7c32e1406a3c178deb7285',
    messagingSenderId: '804095641312',
    projectId: 'folder-ver2',
    storageBucket: 'folder-ver2.appspot.com',
    iosBundleId: 'com.example.folder',
  );
}
